Repository Nandosts/Ressaca-trainee, pull requests merged in 2020-07, with the labels that each got.

#71 Adresses to purchases
  app/controllers/addresses_controller.rb
  app/controllers/purchases_controller.rb
  app/controllers/users_controller.rb
  app/views/addresses/_form.html.erb
  app/views/purchases/cart.html.erb
  app/views/purchases/index.html.erb
  app/views/users/show.html.erb
  config/routes.rb
  db/migrate/20200707201512_add_erased_to_addresses.rb
  db/schema.rb
Labels: enhancement

#73 Improve add funds view
  app/assets/stylesheets/perfil.scss
  app/views/users/_add_money.html.erb
  app/views/users/add_money.html.erb
  app/views/users/show.html.erb
Labels: enhancement

#70 View form produtos
  app/assets/stylesheets/product_form.scss
  app/controllers/products_controller.rb
  app/views/products/_form.html.erb
  app/views/products/_show_admin.html.erb
  app/views/products/edit.html.erb
  app/views/products/new.html.erb
  config/initializers/assets.rb
Labels: enhancement

#79 Ordenar produtos na pesquisa
  app/assets/stylesheets/search.scss
  app/controllers/products_controller.rb
  app/views/products/search.html.erb
  config/routes.rb
Labels: enhancement

#81 Correção de bugs simples do carrinho
  app/controllers/addresses_controller.rb
  app/controllers/products_controller.rb
  app/controllers/purchase_products_controller.rb
  app/controllers/purchases_controller.rb
  app/views/purchases/cart.html.erb
  app/views/users/show.html.erb
  db/migrate/20200710234521_change_erased_to_visible.rb
  db/migrate/20200710235356_add_visible_to_products.rb
  db/schema.rb
Labels: bug

#92 pagina do produto agora é de responsabilidade rapaz
  app/views/products/_show_admin.html.erb
  app/views/products/_show_user.html.erb
Labels: enhancement

#93 Com grandes projetos, vêm grandes responsividades
  app/assets/stylesheets/login.scss
  app/assets/stylesheets/perfil.scss
  app/views/user_sessions/new.html.erb
  app/views/users/_form.html.erb
  app/views/users/show.html.erb
Labels: enhancement

#96 Popups adicionados para os flashes
  app/assets/javascripts/application.js
  app/assets/stylesheets/application.css.scss
  app/controllers/addresses_controller.rb
  app/controllers/application_controller.rb
  app/controllers/drink_types_controller.rb
  app/controllers/products_controller.rb
  app/controllers/purchase_products_controller.rb
  app/controllers/purchases_controller.rb
  app/controllers/user_sessions_controller.rb
  app/controllers/users_controller.rb
  app/helpers/application_helper.rb
  app/views/layouts/application.html.erb
Labels: enhancement

#98 Bugfix
  app/assets/stylesheets/card.scss
  app/assets/stylesheets/navbar.scss
  app/views/layouts/application.html.erb
  app/views/products/search.html.erb
Labels: bug, enhancement
